# Generated by IBM TransformationAdvisor
# Wed Nov 16 14:18:47 UTC 2022

FROM maven:3.6.3-jdk-8-openj9 AS build-stage

COPY . /project
WORKDIR /project

#RUN mvn process-resources

RUN mkdir -p /config/lib && \
     cp ./target/*.*ar /config && \
     if [ -d "./target/lib" ]; then \
         cp ./target/lib/*.* /config/lib; \
     fi

FROM ibmcom/websphere-traditional:latest-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root --from=build-stage /config /work/config
COPY --chown=was:root ./src/config /work/config
#COPY --chown=was:root --from=build-stage ./lib /work/config/lib
RUN /work/configure.sh
